name = "Lean Topology game2"
version = "1.1.0"
extra_files = "extras"
intro = "src/intro.lean"


[[worlds]]
name = "Set theory"
id = 1
levels = [ "src/set_theory_world/level01.lean" ]

[[worlds]]
name = "Functions"
id = 2
parents = [1]
levels = [ "src/function_world/level1.lean" ]

[[worlds]]
name = "Basic definitions"
id = 3
parents = [2]
levels = [ "src/basic_defs_world/level1.lean" ]

[[worlds]]
name = "Interior world"
id = 4
parents = [3]
levels = [ "src/interior_world/level1.lean" ]

